### PR TITLE
Add auto indent

### PR DESCRIPTION
**Pull request by zai1208**
If I can't create it myself at least I can contribute to an extension created by someone else

### CODE REVIEW

**Comment by foxoman** [comment]
Great thank you very much, I appreciate your kindness in supporting this project, let us work together to make nim support as good as it can be. 

- I will review your commit and merged after , please stay tuned

**Review by zai1208 — COMMENTED** [review]
Added regex to increase and decrease indent

**Comment by zai1208** [comment]
I have not used pull requests before

**Comment by foxoman** [comment]
Thank you very much, let me know if your last changes are final before I test and merge, please.

**Comment by zai1208** [comment]
This was the final commit. Auto indenting and unindenting is now fully functional

**Comment by zai1208** [comment]
auto indenting works for:
- `if`
- `when`
- `proc`
- `elif`
- `else`
- `macro`

The following when they are alone
- `let`
- `var`
- `const`

And `:` if it is at the end of a line

And it unindents on an empty line

**Comment by foxoman** [comment]
Thank you very much,  I will merge it now and will keep fixing the missing things one by one.

**Pull request merged**
